### ISSUE TITLE
データベースへの直接接続

### ISSUE THREAD

**Issue by darkcrash** [chack411/CongestionMonitor#9]
すごく、シンプルでわかりやすいですね！

ただ、運用を想定した時にクライアントアプリから直接DBをアクセスすることに、少し懸念があります。

接続元を特定できない状況下では、不正なアクセスによりDBを破壊されてしまう可能性がないか。

それらに対して、何らかのアクセス権を設定することで回避するか、webapiなどが間にあるといいように思えました。

**Comment by chack411** [comment]
コメントありがとうございます！
DBへのアクセスは、おっしゃるとおりで、本番運用などを想定するとWeb APIなどを介したアクセスが良いと思います。今回、このリポジトリはサンプルコード的な位置付けがあるので、なるべく必要最小限でシンプルにしたかったのと、いまのところCosmosDBはChange Feedの為だけに使っていることもあり、今回はクライアント側からの直接アクセスにしています。
（でも、今後どこかのタイミングで何か考えるかも知れません）

Thank you for your comment!

Yes, that's right. As you said, accessing the Cosmos DB through Web API, API gateway, etc is the better way for a production environment. 
I have positioned this repo as a sample code. So I wanted to keep these codes as simple as possible, and also Cosmos DB is used only for change feed at this time. That's why I decided that client application access to Cosmos DB and Face API directly.

**Comment by darkcrash** [comment]
ご返信ありがとうございます

サンプルコードであり、FaceAPI、CosmosDB、並びに変更フィードへの理解のしやすさを考慮したものであるとのことで、承知いたしました。
